---
# tasks file for roles/configure-pen/
- name: Create init pen directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/pen"
    state: directory
    mode: '0750'

- name: Install machines folder
  ansible.builtin.include_tasks:
    file: machines.yml

- name: Install vpn folder
  ansible.builtin.include_tasks:
    file: vpn.yml

- name: Install wordlists folder
  ansible.builtin.include_tasks:
    file: wordlists.yml

- name: Install payloads folder
  ansible.builtin.include_tasks:
    file: payloads.yml