---
- name: "Customize Kali Linux"
  hosts: localhost
  connection: local
  tasks:
#    - name: Display Ansible Environment Variables
#      debug:
#        var: hostvars[inventory_hostname]
  roles:
    - role: "roles/configure-pen/"
    - role: "roles/configure-system/"
    - role: "roles/configure-tools/"
    - role: "roles/configure-software/"