---
# tasks file for configure-tmux
- name: "Install tmux"
  become: true
  become_method: sudo
  apt:
    name: tmux
    state: present
  

- name: "Copy tmux config"
  copy:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "{{ ansible_env.HOME }}"