---
- name: Check latest Obsidian version
  uri:
    url: https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest
    return_content: true
  register: obsidian_latest

- name: "Download Obsidian"
  loop: "{{ obsidian_latest.json.assets }}"
  when: "'_amd64.deb' in item.name"
  ansible.builtin.get_url:
    url: "{{ item.browser_download_url }}"
    dest: "/tmp/Obsidian.deb"

- name: Install Obsidian .deb package
  become: true
  become_method: sudo
  ansible.builtin.apt:
    deb: /tmp/Obsidian.deb